# Generated by Django 2.0.13 on 2019-04-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200, null=True)),
                ('container', models.CharField(max_length=200, null=True)),
                ('flavor', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
